Connect to database/MVCDEMO/MVCDEMO/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVCDEMO.Models
{
    public class Book
    {
        [Key]
        [ScaffoldColumn(false)]

        public int Id { get; set; }

        [Display(Name="Book Name")]
        [Required(ErrorMessage ="Name is Required")]
        public string Name { get; set; }


        [Display(Name="AuthorName")]
        [Required(ErrorMessage ="AuthorName is Required")]
        public string AuthorName { get; set; }

        [Display(Name="PublisherName")]
        [Required(ErrorMessage ="PublisherName is required")]
        public string PublisherName { get; set; }

        [Required(ErrorMessage ="Date is Required")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage ="Price is Required")]
        [Range(minimum:100,maximum:1000,ErrorMessage ="Price Between 100-1000")]
        public int Price { get; set; }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Models/ErrorViewModel.cs
using System;

namespace MVCDEMO.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Connect to database/MVCDEMO/MVCDEMO/Models/Product.cs
using System;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Company { get; set; }
    public double Price { get; set; }
}

Connect to database/MVCDEMO/MVCDEMO/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace MVCDEMO.Models
{
    public class Student
    {
        [Key]
        [ScaffoldColumn(false)]
        public int RollNo { get; set; }

        [Display(Name ="Student Name")]
        [Required(ErrorMessage ="Name is Required")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Age is Required")]
        [Range(minimum:18, maximum:60,ErrorMessage ="Age should be between 18 to 60")]
        public int Age { get; set; }

        [Required(ErrorMessage ="EmailId is required")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Email Id is not in proper format")]
        public string EmailId { get; set; }

        [Required(ErrorMessage ="City is required")]
        [MaxLength(20)]
        public string City { get; set; }

        [Required(ErrorMessage ="Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDEMO.Models;

namespace MVCDEMO.Controllers
{
    public class BookController : Controller
    {
        public IActionResult AddBook()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBook(Book book)
        {
            return View();
        }

    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVCDEMO.Controllers
{
    public class EmployeeController : Controller
    {
        [HttpGet]
        public IActionResult EmployeeDetails()
        {
            List<string> Options = new List<string>();
            Options.Add("Choose Designation");
            Options.Add("Front End Developer");
            Options.Add("BackEnd Developer");
            Options.Add("Data Scientist");
            Options.Add("Data Analysist");
            ViewData["Options"] = new SelectList(Options);
            return View();
        }

        [HttpPost]
        public ActionResult EmployeeDetails(IFormCollection fc, ICollection<string>  Location)
        {
            ViewBag.EmpName = fc["EmpName"];
            ViewBag.EmpId = fc["EmpId"];
            ViewBag.MobileNumber = fc["phone"];
            ViewBag.salary = fc["salary"];
            ViewBag.gender = fc["gender"];
            ViewBag.Location = fc["Location"];
            ViewBag.Designation = fc["Options"];
            return View("EmpDetails");

        }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCDEMO.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDEMO.Controllers
{
    public class  HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/PersonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;


namespace MVCDEMO.Controllers
{
    public class PersonController : Controller
    {
        [HttpGet]

        public IActionResult Personaldetails()
        {
            List<string> Options = new List<string>();
            Options.Add("Choose an Option");
            Options.Add("Yes");
            Options.Add("No");
            ViewData["Options"] = new SelectList(Options);
            return View();
        }
        [HttpPost]

        public ActionResult PersonalDetails(IFormCollection fc, ICollection<string> hobbies)
        {
            ViewBag.firstname = fc["Firstname"];
            ViewBag.lastname = fc["lastname"];
            ViewBag.phone = fc["phone"];
            ViewBag.gender = fc["gender"];
            ViewBag.hobbies = fc["hobbies"];
            ViewBag.options = fc["options"];
            return View("Details");

        }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

using  MVCDEMO.Models;
namespace MVCDEMO.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult GetAllProduct()
        {
            List<Product> productlist = new List<Product>()
            {
                new Product{Id=1,Name="Laptop",Company="Dell",Price=40000},
                new Product{Id=2,Name="Laptop",Company="HP",Price=50000},
                new Product{Id=3,Name="Laptop",Company="Lenovo",Price=30000},
                new Product{Id=4,Name="Mouse",Company="Dell",Price=400},
                new Product{Id=5,Name="Keyword",Company="Dell",Price=700},
            };
            ViewBag.ProductList = productlist;
            return View();
        }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDEMO.Models;

namespace MVCDEMO.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult AddStudent()
        {
            return View();

        }
        [HttpPost]
       public ActionResult AddStudent(Student student)
        {
            return View();
        }
    }
}

Connect to database/MVCDEMO/MVCDEMO/Views/Book/AddBook.cshtml
@model MVCDEMO.Models.Book

@{
    ViewData["Title"] = "AddBook";
}

<h1>AddBook</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBook">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" />
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label"></label>
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Connect to database/MVCDEMO/MVCDEMO/Views/Product/GetAllProduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Company</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Product product in ViewBag.ProductList)
        {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            <td>@product.Company</td>
            <td>@product.Price</td>
        </tr>
        }
    </tbody>
</table>

Connect to database/MVCDEMO/MVCDEMO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDEMO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDEMO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetAllProduct">Get All Products</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonalDetails">Personal Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeDetails">Employee Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="AddStudent">Student Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="AddBook">New Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDEMO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Connect to database/MVCDEMO/MVCDEMO/Views/Student/AddStudent.cshtml
@model MVCDEMO.Models.Student

@{
    ViewData["Title"] = "AddStudent";
}

<h1>AddStudent</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddStudent">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailId" class="control-label"></label>
                <input asp-for="EmailId" class="form-control" />
                <span asp-validation-for="EmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>